### ISSUE TITLE
There is no such command as "spk-seg".

### ISSUE THREAD

**Issue by ketan4373** [usc-sail/mica-gender-from-audio#3]
I am trying to run ./generate_gender_pred.sh but it's not executing properly as there is no such command or file for speaker segmentation. Please help me out on this. Thanks.

**Comment by rabbeh** [comment]
We have replaced the kaldi-binary for BIC-based segmentation with a tunable uniform-segmentation. Please note the necessity for segmentation in our script: we cast a majority vote of Gender ID labels over a segment, hence its necessary to separate continuous speech from multiple speakers which is detected as a single SAD segment.
